#!/bin/sh
#SBATCH --job-name=5_IRandNMR
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=5_IRandNMR.err
#SBATCH --time=00:20:00


# Activate it
source $VSC_SCRATCH/venvs/irc_temp_env/bin/activate


# Link or copy sgx16 into this folder
ln -sf ./Scripts/sgx16 .

# Make sure it's executable (redundant if done already)
chmod +x sgx16

#Launching calculation
chmod 777 Automated_IRandNMR.py
python Automated_IRandNMR.py
