#!/bin/sh
#SBATCH --job-name=ConfoWoerpelMe
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=ConfoWoerpelMe.logfile
#SBATCH --time=10:00:00

#Defining Gaussian Parameters
cd $VSC_SCRATCH/lise/13_Ondemand/Fulvenes/Fullstructure/Test

#Loading modules
module load sPyRMSD/0.8.0-foss-2023a
module load openpyxl/3.1.2-GCCcore-12.3.0

#Launching calculation
chmod 777 Automated_IRC_Calculation.py
python Automated_IRC_Calculation.py

