#!/bin/sh
#SBATCH --job-name=ConfoWoerpelMe
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=ConfoWoerpelMe.logfile
#SBATCH --time=01:00:00

#Defining Gaussian Parameters
export PATH=/vscmnt/brussel_pixiu_home/_user_brussel/105/vsc10536/bin/:$PATH

#Loading modules
module load sPyRMSD/0.8.0-foss-2023a
module load openpyxl/3.1.2-GCCcore-12.3.0

#Launching calculation
chmod 777 Automated_IRC_Extractor.py
python Automated_IRC_Extractor.py

