#!/bin/sh
#SBATCH --job-name=SeparateReagents
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=4_SeparateReagents.logfile
#SBATCH --time=00:20:00

#Opening correct folder
cd $VSC_SCRATCH/lise/13_Ondemand/Paul/automateddielsalder/Correction/

#Defining Gaussian Parameters
export PATH=/vscmnt/brussel_pixiu_home/_user_brussel/105/vsc10536/bin/:$PATH


#Loading modules
module load openpyxl/3.1.2-GCCcore-12.3.0
module load matplotlib/3.7.2-gfbf-2023a

#Launching calculation
chmod 777 Automated_Reagents.py
python Automated_Reagents.py
