#!/bin/sh
#SBATCH --job-name=4_SeparateReagents
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=4_SeparateReagents.err
#SBATCH --time=00:20:00

# Define virtual environment path
VENV_DIR="$VSC_SCRATCH/venvs/irc_temp_env"


# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Link or copy sgx16 into this folder
ln -sf ./Scripts/sgx16 .

# Make sure it's executable (redundant if done already)
chmod +x sgx16

#Launching calculation
chmod 777 Automated_Reagents.py
python Automated_Reagents.py
